server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://47.115.216.83:3306/lol?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: develop
    password: develop
    driver-class-name: com.mysql.cj.jdbc.Driver